# Problem 1

In [12]:
import numpy as np

#Setting the variables to random reproducibility
np.random.seed(42)

# This creates a 5x5 array
s_random = np.random.rand (5, 5)
print ("The Original array:")
print (s_random)
print ()

# For the computation of the mean and standard deviation
std_s = np.std(s_random)
# For the mean
mean_s = np.mean(s_random)

#Normalizing the array
s_norm = (s_random - mean_s)/std_s

print ("The normalized array:")
print (s_norm)

The Original array:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

The normalized array:
[[-0.23709911  1.82467557  1.04200929  0.56488331 -1.01905371]
 [-1.01914002 -1.36950322  1.52216525  0.57367372  0.95640937]
 [-1.5036896   1.89336468  1.40145369 -0.81751722 -0.92670866]
 [-0.92105645 -0.48865218  0.30043311 -0.03168212 -0.5352181 ]
 [ 0.61209803 -1.07818578 -0.53194206 -0.26636415  0.05464636]]


# Problem 2

In [13]:
import numpy as np

# Create the array of the first 100 positive integers
digit = np.arange (1,101)

# Squaring the elements (boxing them)
box = digit ** 2

# Make the array into a 10x10 array
ar = box.reshape(10, 10)
print("The Array A of the first 100 integers:")
print(ar)
print()

#
divisible = ar[ar % 3 == 0]
print("The elements are divisible by 3:")
print (divisible)

# Requirement to save by div_by_3
np.save('div_by_3.npy', div_by_3)

The Array A of the first 100 integers:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

The elements are divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
